version: '3'

services:
  mysql:
    image: mysql:8
    container_name: laravel_db
    environment:

      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
    ports:
      - "127.0.0.1:33061:3306"
    volumes:
      - ./docker/local-nginx/tmp/db:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: docker/local-nginx/Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www/html

  nginx:
    image: nginx:latest
    container_name: laravel_web
    ports:
      - "8080:80"
    volumes:
      - ./docker/local-nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html/public
      - ./storage/app/public:/var/www/html/storage/app/public





